name: filemaker_appwrite
description: filemaker data api library used in appwrite functions
version: 1.0.2
# homepage: https://www.example.com
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  dart_appwrite: ^4.0.1
  dio: ^4.0.4
  intl: ^0.17.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
